Repository brain-tec/serpentcs_contributions-v8, pull requests merged in 2024-09, with the labels that each got.

#309 Syncing from upstream JayVora-SerpentCS/SerpentCS_Contributions (16.0)
  import_export_templating/README.rst
  import_export_templating/__manifest__.py
  import_export_templating/static/description/Banner-Import  Export Templating-16.png
  import_export_templating/static/description/banner01.jpg
  import_export_templating/static/description/banner01.png
  import_export_templating/static/description/header-logo.png
  import_export_templating/static/description/icon.png
Labels: 16.0

#310 [bt#28589] Optimize fetching of data from /web/fetch_x2m_data
  web_one2many_kanban/static/src/js/web_one2many_kanban.js
Labels: 13.0.project_pr_449

#312 Syncing from upstream JayVora-SerpentCS/SerpentCS_Contributions (17.0)
  hr_grade_rank/__manifest__.py
  hr_grade_rank/static/description/Banner_hr_grade_rank.png
  hr_grade_rank/static/description/icon.png
  hr_grade_rank/static/description/icon1.png
  project_detail_report/__manifest__.py
  project_detail_report/static/description/Banner_project_detail_report.png
  project_detail_report/static/description/icon.png
  project_detail_report/static/description/icon1.png
  project_kanban/__manifest__.py
  project_kanban/static/description/Banner_project_kanban.png
  project_kanban/static/description/header-logo.png
  project_kanban/static/description/icon.png
  project_kanban/static/description/icon1.png
  project_task_detail_report/__manifest__.py
  project_task_detail_report/static/description/Banner_project_task_detail_report.png
  project_task_detail_report/static/description/header-logo.png
  project_task_detail_report/static/description/icon.png
  project_task_detail_report/static/description/icon1.png
Labels: 17.0
